function statAssignInt()
    -- Blood Mage
    udg_Stat_Assign_Unit_Type[1] = "Hblm"
    udg_Stat_Health_Assign[1] = 456
    udg_Stat_Mana_Assign[1] = 654
    udg_Stat_Strength_Assign[1] = 11
    udg_Stat_Agility_Assign[1] = 24
    udg_Stat_Intelligence_Assign[1] = 65
    udg_Stat_Health_Regen_Assign[1] = 1.00
    udg_Stat_Mana_Regen_Assign[1] = 1.00
    udg_Stat_Armor_Assign[1] = 69
    udg_Stat_Critical_Chance_Assign[1] = 60.00
    udg_Stat_Critical_Damage_Rate_As[1] = 1.00
    udg_Stat_Dodge_Assign[1] = 3.00
    udg_Stat_Parry_Assign[1] = 3.00
    udg_Stat_Block_Assign[1] = 3.00
    udg_Stat_Block_Enabled_Assign[1] = 0
    udg_Stat_Miss_Assign[1] = 0.00
    udg_Stat_Attack_Damage_Assign[1] = 29
    udg_Stat_Spell_Damage_Assign[1] = 666
    -- Knight
    udg_Stat_Assign_Unit_Type[2] = "hkni"
    udg_Stat_Health_Assign[2] = 9998
    udg_Stat_Mana_Assign[2] = 654
    udg_Stat_Strength_Assign[2] = 55
    udg_Stat_Agility_Assign[2] = 25
    udg_Stat_Intelligence_Assign[2] = 10
    udg_Stat_Health_Regen_Assign[2] = 2.00
    udg_Stat_Mana_Regen_Assign[2] = 2.00
    udg_Stat_Armor_Assign[2] = 15
    udg_Stat_Critical_Chance_Assign[2] = 0.45
    udg_Stat_Critical_Damage_Rate_As[2] = 5.00
    udg_Stat_Dodge_Assign[2] = 3.00
    udg_Stat_Parry_Assign[2] = 3.00
    udg_Stat_Block_Assign[2] = 3.00
    udg_Stat_Block_Enabled_Assign[2] = 0
    udg_Stat_Miss_Assign[2] = 0.00
    udg_Stat_Attack_Damage_Assign[2] = 11
    udg_Stat_Spell_Damage_Assign[2] = 0
    -- Heroes
    udg_Stat_Assign_Unit_Type[3] = "H004"
    udg_Stat_Assign_Unit_Type[4] = "H005"
    udg_Stat_Assign_Unit_Type[5] = "H006"
    udg_Stat_Assign_Unit_Type[6] = "H007"
    udg_Stat_Assign_Unit_Type[7] = "H008"
    udg_Stat_Assign_Unit_Type[8] = "H009"
    udg_Stat_Assign_Unit_Type[9] = "H00A"
    udg_Stat_Assign_Unit_Type[10] = "H00B"
    udg_Stat_Assign_Unit_Type[11] = "H00C"
    udg_Stat_Assign_Unit_Type[12] = "H00D"
    udg_Stat_Assign_Unit_Type[13] = "H00E"
    udg_Stat_Assign_Unit_Type[14] = "H00F"
    udg_Stat_Assign_Unit_Type[15] = "H00G"
    udg_Stat_Assign_Unit_Type[16] = "H00H"
    udg_Stat_Assign_Unit_Type[17] = "H00I"
    udg_Stat_Assign_Unit_Type[18] = "H00J"
    udg_Stat_Assign_Unit_Type[19] = "H00K"
    udg_Stat_Assign_Unit_Type[20] = "H00L"
    for i=3,20 do
        udg_Stat_Health_Assign[i] = 525
        udg_Stat_Mana_Assign[i] = 235
        udg_Stat_Strength_Assign[i] = 14
        udg_Stat_Agility_Assign[i] = 14
        udg_Stat_Intelligence_Assign[i] = 14
        udg_Stat_Health_Regen_Assign[i] = 5.00
        udg_Stat_Mana_Regen_Assign[i] = 5.00
        udg_Stat_Armor_Assign[i] = 10
        udg_Stat_Critical_Chance_Assign[i] = 3.00
        udg_Stat_Critical_Damage_Rate_As[i] = 1
        udg_Stat_Dodge_Assign[i] = 3.00
        udg_Stat_Parry_Assign[i] = 3.00
        udg_Stat_Block_Assign[i] = 3.00
        udg_Stat_Block_Enabled_Assign[i] = 0
        udg_Stat_Miss_Assign[i] = 3.00
        udg_Stat_Attack_Damage_Assign[i] = 0
        udg_Stat_Spell_Damage_Assign[i] = 0
    end

    -- Limit
    udg_Stat_Assign_Limit = 20
end